import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getAuthSession, unauthorized, badRequest } from "@/lib/api-utils";
import { skillOrchestrator } from "@/lib/skill-orchestrator";
import { daftarEvents } from "@/lib/event-bus";

/**
 * POST /api/pipeline/trigger
 *
 * The Khabri → Yantri → Relay pipeline trigger.
 * Accepts a signal/trend and runs it through the signal-to-deliverable workflow:
 *   1. Brand relevance check (which brands should cover this?)
 *   2. Editorial decision (angle, urgency, formats)
 *   3. Research (fact dossier via skills)
 *   4. Narrative construction (drafts per format)
 *   5. Task creation in PMS
 *   6. Queue for Relay distribution on approval
 */
export async function POST(req: NextRequest) {
  const session = await getAuthSession();
  if (!session) return unauthorized();

  const body = await req.json();
  const { signalId, trendTitle, summary, brandIds, urgency } = body;

  if (!trendTitle) {
    return badRequest("trendTitle is required");
  }

  // Determine target brands — if not specified, check all active brands
  let brands;
  if (brandIds && brandIds.length > 0) {
    brands = await prisma.brand.findMany({
      where: { id: { in: brandIds } },
      include: { platforms: { where: { isActive: true } } },
    });
  } else {
    brands = await prisma.brand.findMany({
      include: { platforms: { where: { isActive: true } } },
    });
  }

  const results = [];

  for (const brand of brands) {
    // Stage 1: Brand relevance check via skill
    const relevanceResult = await skillOrchestrator.executeSkill({
      skillPath: "narrative/editorial/topic-selection.md",
      context: {
        signal: { title: trendTitle, summary, urgency: urgency || "normal" },
        brand: { id: brand.id, name: brand.name, slug: brand.slug },
        platforms: brand.platforms.map((p) => p.platform),
      },
      brandId: brand.id,
    });

    const shouldCover = relevanceResult.success &&
      (relevanceResult.output as Record<string, unknown>)?.shouldCover !== false;

    if (!shouldCover) {
      results.push({ brandId: brand.id, brandName: brand.name, action: "skipped", reason: "Not relevant" });
      continue;
    }

    // Stage 2: Editorial decision
    const editorialResult = await skillOrchestrator.executeSkill({
      skillPath: "narrative/editorial/narrative-framing.md",
      context: {
        signal: { title: trendTitle, summary },
        brand: { id: brand.id, name: brand.name },
        platforms: brand.platforms.map((p) => p.platform),
      },
      brandId: brand.id,
    });

    // Stage 3: Create tasks for each platform deliverable
    const platformTasks = [];
    for (const bp of brand.platforms) {
      const task = await prisma.task.create({
        data: {
          title: "[Pipeline] " + trendTitle + " — " + bp.platform,
          description: "Auto-generated by Khabri→Yantri pipeline.\n\nSignal: " + trendTitle + "\nSummary: " + (summary || "N/A") + "\nEditorial: " + JSON.stringify(editorialResult.output || {}),
          priority: urgency === "breaking" ? "URGENT" : urgency === "high" ? "HIGH" : "MEDIUM",
          status: "TODO",
          creatorId: session.user.id,
          brandId: brand.id,
        },
      });
      platformTasks.push({ taskId: task.id, platform: bp.platform });
    }

    // Emit event for GI and other listeners
    daftarEvents.emitEvent("pipeline.triggered", {
      signalId,
      trendTitle,
      brandId: brand.id,
      brandName: brand.name,
      tasksCreated: platformTasks.length,
      triggeredBy: session.user.id,
    });

    results.push({
      brandId: brand.id,
      brandName: brand.name,
      action: "triggered",
      tasksCreated: platformTasks,
      editorial: editorialResult.output,
    });
  }

  return NextResponse.json({
    success: true,
    pipeline: "khabri-yantri-relay",
    signal: { title: trendTitle, summary },
    results,
  });
}
