import type { Role } from "@prisma/client";
import type { SidebarItem } from "@/types";

export const SIDEBAR_ITEMS: SidebarItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    href: "/dashboard",
    roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD", "MEMBER", "CLIENT", "FINANCE", "CONTRACTOR"],
  },
  {
    id: "my-tasks",
    label: "My Tasks",
    icon: "CheckSquare",
    href: "/tasks",
    roles: ["MEMBER", "CONTRACTOR"],
  },
  {
    id: "my-brands",
    label: "My Brands",
    icon: "Palette",
    href: "/brands",
    roles: ["CLIENT"],
  },
  {
    id: "khabri",
    label: "Khabri",
    icon: "Newspaper",
    href: "/m/khabri",
    roles: ["ADMIN", "DEPT_HEAD", "MEMBER"],
    children: [
      { id: "khabri-dashboard", label: "Dashboard", icon: "LayoutDashboard", href: "/m/khabri", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "khabri-trends", label: "Trends", icon: "TrendingUp", href: "/m/khabri/trends", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "khabri-signals", label: "Signals", icon: "Radio", href: "/m/khabri/signals", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "khabri-narratives", label: "Narratives", icon: "GitBranch", href: "/m/khabri/narratives", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "khabri-geo", label: "Geo Intel", icon: "Globe2", href: "/m/khabri/geo", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "khabri-analytics", label: "Analytics", icon: "BarChart3", href: "/m/khabri/analytics", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
    ],
  },
  {
    id: "yantri",
    label: "Yantri",
    icon: "Brain",
    href: "/m/yantri",
    roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD", "MEMBER"],
    children: [
      { id: "yantri-dashboard", label: "Dashboard", icon: "LayoutDashboard", href: "/m/yantri", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-narrative-trees", label: "Narrative Trees", icon: "GitBranch", href: "/m/yantri/narrative-trees", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-trends", label: "Trends", icon: "TrendingUp", href: "/m/yantri/trends", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-workspace", label: "Workspace", icon: "Layers", href: "/m/yantri/workspace", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-dossiers", label: "Dossiers", icon: "FileText", href: "/m/yantri/dossiers", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-deliverables", label: "Deliverables", icon: "Package", href: "/m/yantri/deliverables", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-content-types", label: "Content Types", icon: "Shapes", href: "/m/yantri/content-types", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-prompt-library", label: "Prompts", icon: "FileText", href: "/m/yantri/prompt-library", roles: ["ADMIN", "DEPT_HEAD"] },
      { id: "yantri-platform-rules", label: "Platform Rules", icon: "Settings", href: "/m/yantri/platform-rules", roles: ["ADMIN"] },
      { id: "yantri-history", label: "History", icon: "Clock", href: "/m/yantri/history", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "yantri-performance", label: "Performance", icon: "BarChart3", href: "/m/yantri/performance", roles: ["ADMIN", "DEPT_HEAD"] },
    ],
  },
  {
    id: "relay",
    label: "Relay",
    icon: "Send",
    href: "/relay",
    roles: ["ADMIN", "DEPT_HEAD", "MEMBER", "CLIENT"],
    children: [
      { id: "relay-queue", label: "Queue", icon: "ListOrdered", href: "/relay/queue", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "relay-calendar", label: "Calendar", icon: "Calendar", href: "/relay/calendar", roles: ["ADMIN", "DEPT_HEAD", "MEMBER", "CLIENT"] },
      { id: "relay-analytics", label: "Analytics", icon: "BarChart3", href: "/relay/analytics", roles: ["ADMIN", "DEPT_HEAD", "MEMBER", "CLIENT"] },
    ],
  },
  {
    id: "pms",
    label: "PMS",
    icon: "Kanban",
    href: "/pms",
    roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD", "MEMBER", "CONTRACTOR"],
  },
  {
    id: "hoccr",
    label: "HOCCR",
    icon: "Users",
    href: "/hoccr",
    roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD"],
    children: [
      { id: "hoccr-operations", label: "Operations", icon: "Activity", href: "/hoccr/operations", roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD"] },
      { id: "hoccr-culture", label: "Culture", icon: "Heart", href: "/hoccr/culture", roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD"] },
      { id: "hoccr-hiring", label: "Hiring", icon: "UserPlus", href: "/hoccr/hiring", roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD"] },
      { id: "hoccr-reports", label: "Reports", icon: "BarChart3", href: "/hoccr/reports", roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD"] },
    ],
  },
  {
    id: "communication",
    label: "Communication",
    icon: "MessageCircle",
    href: "/communication",
    roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD", "MEMBER"],
  },
  {
    id: "vritti",
    label: "Vritti",
    icon: "FileText",
    href: "/m/vritti",
    roles: ["ADMIN", "DEPT_HEAD", "MEMBER", "CLIENT"],
    children: [
      { id: "vritti-pipeline", label: "Pipeline", icon: "Kanban", href: "/m/vritti/pipeline", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "vritti-articles", label: "Articles", icon: "FileText", href: "/m/vritti/articles", roles: ["ADMIN", "DEPT_HEAD", "MEMBER", "CLIENT"] },
      { id: "vritti-media", label: "Media", icon: "Image", href: "/m/vritti/media", roles: ["ADMIN", "DEPT_HEAD", "MEMBER"] },
      { id: "vritti-categories", label: "Categories", icon: "Tag", href: "/m/vritti/categories", roles: ["ADMIN", "DEPT_HEAD"] },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    icon: "IndianRupee",
    href: "/finance",
    roles: ["ADMIN", "FINANCE"],
  },
  {
    id: "users",
    label: "Users & Roles",
    icon: "UserCog",
    href: "/admin/users",
    roles: ["ADMIN", "HEAD_HR"],
  },
  {
    id: "departments",
    label: "Departments",
    icon: "Building2",
    href: "/admin/departments",
    roles: ["ADMIN"],
  },
  {
    id: "clients",
    label: "Clients & Brands",
    icon: "Building",
    href: "/admin/clients",
    roles: ["ADMIN", "FINANCE"],
  },
  {
    id: "skills",
    label: "Skills",
    icon: "BookOpen",
    href: "/admin/skills",
    roles: ["ADMIN"],
    children: [
      { id: "skills-list", label: "All Skills", icon: "BookOpen", href: "/admin/skills", roles: ["ADMIN"] },
      { id: "skills-performance", label: "Performance", icon: "BarChart3", href: "/admin/skills/performance", roles: ["ADMIN"] },
    ],
  },
  {
    id: "gi-config",
    label: "GI Intelligence",
    icon: "Sparkles",
    href: "/admin/gi",
    roles: ["ADMIN"],
    children: [
      { id: "gi-overview", label: "Overview", icon: "LayoutDashboard", href: "/admin/gi", roles: ["ADMIN"] },
      { id: "gi-actions", label: "Actions", icon: "Zap", href: "/admin/gi/actions", roles: ["ADMIN"] },
      { id: "gi-predictions", label: "Predictions", icon: "TrendingUp", href: "/admin/gi/predictions", roles: ["ADMIN"] },
      { id: "gi-learning", label: "Learning", icon: "Brain", href: "/admin/gi/learning", roles: ["ADMIN"] },
      { id: "gi-autonomy", label: "Config", icon: "Settings", href: "/admin/gi/config", roles: ["ADMIN"] },
    ],
  },
  {
    id: "saas-admin",
    label: "SaaS Platform",
    icon: "Cloud",
    href: "/admin/saas",
    roles: ["ADMIN"],
    children: [
      { id: "saas-dashboard", label: "Dashboard", icon: "LayoutDashboard", href: "/admin/saas", roles: ["ADMIN"] },
      { id: "saas-onboarding", label: "Onboarding", icon: "UserPlus", href: "/admin/saas/onboarding", roles: ["ADMIN"] },
      { id: "saas-products", label: "Products", icon: "Package", href: "/admin/products", roles: ["ADMIN"] },
    ],
  },
  {
    id: "leaderboard",
    label: "Leaderboard",
    icon: "Trophy",
    href: "/leaderboard",
    roles: ["ADMIN", "DEPT_HEAD", "MEMBER"],
  },
  {
    id: "credibility",
    label: "Credibility",
    icon: "ShieldCheck",
    href: "/credibility",
    roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD", "MEMBER", "CONTRACTOR"],
  },
  {
    id: "calendar",
    label: "Calendar",
    icon: "Calendar",
    href: "/calendar",
    roles: ["ADMIN", "DEPT_HEAD", "MEMBER", "CLIENT"],
  },
  {
    id: "reports",
    label: "Reports",
    icon: "BarChart3",
    href: "/reports",
    roles: ["ADMIN", "HEAD_HR", "DEPT_HEAD", "CLIENT", "FINANCE"],
  },
];

export function getSidebarItemsForRole(role: Role): SidebarItem[] {
  return SIDEBAR_ITEMS.filter((item) => item.roles.includes(role));
}
